### ISSUE TITLE
the old hashie_rails works, but this new hashie-fobbidden_attributes doesn't work

### ISSUE THREAD

**Issue by alucardpj** [Maxim-Filimonov/hashie-forbidden_attributes#3]
I just change the Gemfile from
gem 'hashie_rails'
to
gem 'hashie-forbidden_attributes'

and bundle install

but it doesn't work using the new gem. It will raise ActiveModel::ForbiddenAttributesError.

Should I do any extra configuration?

**Comment by peikk0** [comment]
Same here

**Comment by dblock** [comment]
Oh my, we should have actually tested the renamed gem :( I have a fix, will yank the released 1.0, hold on.

**Comment by dblock** [comment]
Yanked 0.1.0, release 0.1.1, this time tested with an actual Rails app. LMK if you're still seeing issues and sorry about that.

**Comment by peikk0** [comment]
It works, thanks. :)
