### ISSUE TITLE
Hashie::Mash.respond_to?(:permitted?)  returns true

### ISSUE THREAD

**Issue by rahul** [Maxim-Filimonov/hashie-forbidden_attributes#6]
I'm using Rails 4.2.4, Grape 0.14.0, Hashie 3.4.3

I included this gem but `params` or any instance of `Hashie::Mash` continues to return `true` for `respond_to?(:permitted?)`

```
> Hashie::Mash.new.respond_to?(:permitted?)
=> true
```

**Comment by dblock** [comment]
I don't see how, see https://github.com/Maxim-Filimonov/hashie-forbidden_attributes/blob/master/lib/hashie-forbidden_attributes/hashie/mash.rb. You'll have to debug what's going on.

**Comment by Maxim-Filimonov** [comment]
Closing due to long inactivity
